# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet ef migrations script -i -o $(Build.ArtifactStagingDirectory)migrate.sql --project Itan.Database\Itan.Database.csproj --startup-project Itan.Database\Itan.Database.csproj
  displayName: 'dotnet ef migrations'
