# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  project: 'Itan.Database/Itan.Database.csproj'

steps:
  - task: UseDotNet@2
    inputs:
        version: '3.1.200'
  - task: DotNetCoreCLI@2
    inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global dotnet-ef'

  - task: DotNetCoreCLI@2
    inputs:
        command: 'custom'
        custom: 'ef'
        arguments: 'migrations list --project $(project) --startup-project $(project) --msbuildprojectextensionspath obj/local'
  - task: DotNetCoreCLI@2
    inputs:
        command: 'custom'
        custom: 'ef'
        arguments: 'migrations script -i -o $(Build.ArtifactStagingDirectory)\migration.sql --project $(project) --startup-project $(project)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'artifact.itan.database'


