# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'b918893e-404a-4a7a-a31a-f3789b8a5c47'
  project: Itan.Functions/Itan.Functions.csproj
  buildConfiguration: 'Release'

  # Function app name
  functionAppName: 'itan-app-service-function'

  # Agent VM image name
  vmImageName: 'vs2017-win2016'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/Itan.Functions'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(project)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'artifact.itan.functions'
