# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureKeyVault@1
  displayName: Fetch AKV
  inputs:
    azureSubscription: 'PAYG (itan) (jarek@codeblast.pl)'
    KeyVaultName: 'itan-key-vault'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: PowerShell@2
  displayName: Set enviroment variable
  inputs:
    targetType: inline
    script: |
      Write-Host '##vso[task.setvariable variable=var-6]"$(SqlAdminConnectionString)"'

- task: DotNetCoreCLI@2
  continueOnError: true
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef'

- task: DotNetCoreCLI@2
  displayName: 'Create migration'
  continueOnError: true
  inputs:
    command: custom
    custom: ef
    arguments: 'migrations script -i -o migration.sql' 
    workingDirectory: 'Itan.Database'

- task: PublishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
