trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureKeyVault@1
  displayName: Fetch AKV
  inputs:
    azureSubscription: 'PAYG (itan) (jarek@codeblast.pl)'
    KeyVaultName: 'itan-key-vault'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: PowerShell@2
  displayName: Set enviroment variable
  inputs:
    targetType: inline
    script: |
      Write-Host '##vso[task.setvariable variable=var-6]"$(SqlAdminConnectionString)"'

- task: DotNetCoreCLI@2
  continueOnError: true
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'PAYG (itan) (jarek@codeblast.pl)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'dotnet ef migrations list --project $(project) --startup-project $(project) --msbuildprojectextensionspath Itan.Database/obj/local'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'PAYG (itan) (jarek@codeblast.pl)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'dotnet ef migrations script -i -o $(Build.ArtifactStagingDirectory)\migration.sql --project $(project) --startup-project $(project) --msbuildprojectextensionspath obj/local'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'artifact.itan.database'